export const CLICK_ELEMENT = "CLICK_ELEMENT";
export const RESET_SELECTED_IDS = "RESET_SELECTED_IDS";
export const REGISTER_ELEMENTREF_FOR_ID = "REGISTER_ELEMENTREF_FOR_ID";
export const SET_SPAREPARTS_DATA = "SET_SPAREPARTS_DATA";
export const SET_SVG_VIEWBOX = "SET_SVG_VIEWBOX";
export const SET_BOTTOM_SHEET_HEIGHT = "SET_BOTTOM_SHEET_HEIGHT";



